<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Charles Lane">

<title>ST558_HW5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST558_HW5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Charles Lane </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="task-1---conceptual-questions" class="level2">
<h2 class="anchored" data-anchor-id="task-1---conceptual-questions">Task 1 - Conceptual Questions</h2>
<section id="question-1-what-is-the-purpose-of-cross-validation-when-fitting-a-random-forest-model" class="level3">
<h3 class="anchored" data-anchor-id="question-1-what-is-the-purpose-of-cross-validation-when-fitting-a-random-forest-model">Question 1: What is the purpose of cross-validation when fitting a random forest model?</h3>
<blockquote class="blockquote">
<p>Selecting a random forest model will result in random predictors used in each bootstrap sample. Cross-validaation is used to determine the best number of predictors to use for the random forest input.</p>
</blockquote>
</section>
<section id="question-2-describe-the-bagged-tree-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="question-2-describe-the-bagged-tree-algorithm">Question 2: Describe the Bagged Tree Algorithm</h3>
<blockquote class="blockquote">
<p>When given a sample set, using the bagged tree algorithm creates subset samples from the original sample called “bootstrap” samples. A model fit is then generated for each bootstrap sample as opposed to the overall sample, and the prediction selected is the average of all bootstrap model predictions generated for the set.</p>
</blockquote>
</section>
<section id="question-3-what-is-meant-by-a-general-linear-model" class="level3">
<h3 class="anchored" data-anchor-id="question-3-what-is-meant-by-a-general-linear-model">Question 3: What is meant by a General Linear Model?</h3>
<blockquote class="blockquote">
<p>Simply put, a General Linear Model is a linear regression model, which is used for samples with normal distributions and can use simple linear regression, or multiple linear regression.</p>
</blockquote>
</section>
<section id="question-4-when-fitting-a-multiple-linear-regression-model-what-does-adding-an-interaction-term-do-that-is-what-does-it-allow-the-model-to-do-differently-as-compared-to-when-it-is-not-included-in-the-model" class="level3">
<h3 class="anchored" data-anchor-id="question-4-when-fitting-a-multiple-linear-regression-model-what-does-adding-an-interaction-term-do-that-is-what-does-it-allow-the-model-to-do-differently-as-compared-to-when-it-is-not-included-in-the-model">Question 4: When fitting a multiple linear regression model, what does adding an interaction term do? That is, what does it allow the model to do differently as compared to when it is not included in the model?</h3>
<blockquote class="blockquote">
<p>An interaction term accounts for the effect of a predictor on the response in the presence of another particular predictor. For example, cholesterol may be seen to have a certain linear relationship to Heart Disease status, but that linear relationship may have a higher or lower slope based on if the predictors are Male or Female. In that sense, an interaction between Sex &amp; Cholesterol would represent this relationship.</p>
</blockquote>
</section>
<section id="question-5-why-do-we-split-our-data-into-a-training-and-test-set" class="level3">
<h3 class="anchored" data-anchor-id="question-5-why-do-we-split-our-data-into-a-training-and-test-set">Question 5: Why do we split our data into a training and test set?</h3>
<blockquote class="blockquote">
<p>If using the same data for both test &amp; training, there is a risk of overtraining the underlying data, or fitting the model too perfectly to the explicit data set used to train. A separate test set is helpful in reducing a metric for error when predicting based on any dataset, not just the given set.</p>
</blockquote>
</section>
</section>
<section id="task-2---fitting-models" class="level2">
<h2 class="anchored" data-anchor-id="task-2---fitting-models">Task 2 - Fitting Models</h2>
<section id="eda-preparation" class="level3">
<h3 class="anchored" data-anchor-id="eda-preparation">EDA / Preparation</h3>
<blockquote class="blockquote">
<p>Load the requisite packages. In order to explore and clean the target data set, I will load tidyverse.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gbm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>####Sub-Task 1: Understanding the Data:</p>
<blockquote class="blockquote">
<p>I will start by reading in the ‘heart’ data from a .csv file downloaded and added to the R repository - “heart.csv”. This file uses comma-delimited values, so the read_csv() function from ‘readr’ package can be used. The spec() function is used to reveal all columns in the dataset and show their data types.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"heart.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 918 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope
dbl (7): Age, RestingBP, Cholesterol, FastingBS, MaxHR, Oldpeak, HeartDisease

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(heart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  Age = col_double(),
  Sex = col_character(),
  ChestPainType = col_character(),
  RestingBP = col_double(),
  Cholesterol = col_double(),
  FastingBS = col_double(),
  RestingECG = col_character(),
  MaxHR = col_double(),
  ExerciseAngina = col_character(),
  Oldpeak = col_double(),
  ST_Slope = col_character(),
  HeartDisease = col_double()
)</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Now that the data has been read into an object, I will create a usable tibble.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(heart)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(heart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
    Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
1    40 M     ATA                 140         289         0 Normal       172
2    49 F     NAP                 160         180         0 Normal       156
3    37 M     ATA                 130         283         0 ST            98
4    48 F     ASY                 138         214         0 Normal       108
5    54 M     NAP                 150         195         0 Normal       122
6    39 M     NAP                 120         339         0 Normal       170
# ℹ 4 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, ST_Slope &lt;chr&gt;,
#   HeartDisease &lt;dbl&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I would like to find the data columns which include NA values. I can use the is.na() function to determine this. I looped through a base vector called “NA_vec” which was simply constructed with column names matching those of the ‘heart’ tibble and vector values associated with each column number. Thus there will be the same number of entries in the vector as there are columns in the heart data set. The loop overwrites those base values with the results of a sum of each time is.na is TRUE within that column. The resulting NA_vec shows no NA values.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>NA_vec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">seq_along</span>(heart))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(NA_vec) <span class="ot">&lt;-</span> <span class="fu">names</span>(heart)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(heart)) {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  NA_vec[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(heart[i]))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>NA_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Age            Sex  ChestPainType      RestingBP    Cholesterol 
             0              0              0              0              0 
     FastingBS     RestingECG          MaxHR ExerciseAngina        Oldpeak 
             0              0              0              0              0 
      ST_Slope   HeartDisease 
             0              0 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>While there are no NA values in the data set. Looking at the heart data set does show several values of 0 for cholesterol. Given that it is reasonable to assume no individual would have a cholesterol measurement of 0, these values can be considered missing, or functionally NA. I will replace these “0” values with NA to avoid confusion in the future.</p>
</blockquote>
<blockquote class="blockquote">
<p>The resulting count of how many Cholesterol measurements are then N/A’ed is calculated specifically for that column.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>heart<span class="sc">$</span>Cholesterol[heart<span class="sc">$</span>Cholesterol<span class="sc">==</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(heart<span class="sc">$</span>Cholesterol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 172</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>There are 918 total observations for this data set and 172 of them are missing Cholesterol measurements. I have removed these NA’ed observations from the data set for future ease.</p>
</blockquote>
<blockquote class="blockquote">
<p>Additionally, the summary() function is used to offer an overview of each variable/column’s attributes.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>heart_2 <span class="ot">&lt;-</span> heart <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heart_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age            Sex            ChestPainType        RestingBP  
 Min.   :28.00   Length:746         Length:746         Min.   : 92  
 1st Qu.:46.00   Class :character   Class :character   1st Qu.:120  
 Median :54.00   Mode  :character   Mode  :character   Median :130  
 Mean   :52.88                                         Mean   :133  
 3rd Qu.:59.00                                         3rd Qu.:140  
 Max.   :77.00                                         Max.   :200  
  Cholesterol      FastingBS       RestingECG            MaxHR      
 Min.   : 85.0   Min.   :0.0000   Length:746         Min.   : 69.0  
 1st Qu.:207.2   1st Qu.:0.0000   Class :character   1st Qu.:122.0  
 Median :237.0   Median :0.0000   Mode  :character   Median :140.0  
 Mean   :244.6   Mean   :0.1676                      Mean   :140.2  
 3rd Qu.:275.0   3rd Qu.:0.0000                      3rd Qu.:160.0  
 Max.   :603.0   Max.   :1.0000                      Max.   :202.0  
 ExerciseAngina        Oldpeak          ST_Slope          HeartDisease   
 Length:746         Min.   :-0.1000   Length:746         Min.   :0.0000  
 Class :character   1st Qu.: 0.0000   Class :character   1st Qu.:0.0000  
 Mode  :character   Median : 0.5000   Mode  :character   Median :0.0000  
                    Mean   : 0.9016                      Mean   :0.4772  
                    3rd Qu.: 1.5000                      3rd Qu.:1.0000  
                    Max.   : 6.2000                      Max.   :1.0000  </code></pre>
</div>
</div>
<p>####Sub-Task 2: Update Data &gt; Given that my ‘HeartDisease’ variable has values of 0 &amp; 1 &amp; is a double() data type, I will update it to be a categorical variable ‘Heart_Disease’ with values of YES or NO, then remove the original ‘HeartDisease’ &amp; ‘STSlope’ variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>heart_3 <span class="ot">&lt;-</span> heart_2 <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Heart_Disease =</span> <span class="fu">ifelse</span>(HeartDisease <span class="sc">==</span> <span class="dv">0</span>, <span class="st">"NO"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ifelse</span>(HeartDisease <span class="sc">==</span> <span class="dv">1</span>,  <span class="st">"YES"</span>, <span class="cn">NA</span>))) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span>HeartDisease <span class="sc">&amp;</span> <span class="sc">!</span>ST_Slope)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>heart_3<span class="sc">$</span>Heart_Disease <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(heart_3<span class="sc">$</span>Heart_Disease)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(heart_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
    Age Sex   ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
1    40 M     ATA                 140         289         0 Normal       172
2    49 F     NAP                 160         180         0 Normal       156
3    37 M     ATA                 130         283         0 ST            98
4    48 F     ASY                 138         214         0 Normal       108
5    54 M     NAP                 150         195         0 Normal       122
6    39 M     NAP                 120         339         0 Normal       170
# ℹ 3 more variables: ExerciseAngina &lt;chr&gt;, Oldpeak &lt;dbl&gt;, Heart_Disease &lt;fct&gt;</code></pre>
</div>
</div>
<section id="sub-task-3-create-numeric-variables" class="level4">
<h4 class="anchored" data-anchor-id="sub-task-3-create-numeric-variables">Sub-Task 3: Create numeric variables</h4>
<blockquote class="blockquote">
<p>For future tasks (using KNN to predict), numeric values are necessary for each predictor. To address my current data set’s character variables, I will use the caret package’s dummyVars() &amp; predict() functions to create representative numeric variables for several character columns, i.e.&nbsp;Sex, ExerciseAngina, ChestPainType, and RestingECG.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dummies <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>(Heart_Disease <span class="sc">~</span> Sex <span class="sc">+</span> ExerciseAngina <span class="sc">+</span> ChestPainType <span class="sc">+</span> RestingECG, <span class="at">data =</span> heart_3)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dum_df <span class="ot">&lt;-</span> <span class="fu">predict</span>(dummies, <span class="at">newdata =</span> heart_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.frame.default(Terms, newdata, na.action = na.action, xlev =
object$lvls): variable 'Heart_Disease' is not a factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dum_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  SexF SexM ExerciseAnginaN ExerciseAnginaY ChestPainTypeASY ChestPainTypeATA
1    0    1               1               0                0                1
2    1    0               1               0                0                0
3    0    1               1               0                0                1
4    1    0               0               1                1                0
5    0    1               1               0                0                0
6    0    1               1               0                0                0
  ChestPainTypeNAP ChestPainTypeTA RestingECGLVH RestingECGNormal RestingECGST
1                0               0             0                1            0
2                1               0             0                1            0
3                0               0             0                0            1
4                0               0             0                1            0
5                1               0             0                1            0
6                1               0             0                1            0</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I’m not sure why the Warning that Heart_Disease is not a factor exists in the preceding output, because it was explicitly made so in preceding actions. A quick test was used to verify:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(heart_3<span class="sc">$</span>Heart_Disease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>At this point, I will continue with next steps and determine if there are any other warnings/errors which occur based on this variable’s factor status.</p>
</blockquote>
<blockquote class="blockquote">
<p>Now to combine the resulting dum_df data set which includes the dummy columns to the original heart_3 data set into a heart_4 data set.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>heart_4 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(heart_3, dum_df)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(heart_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age Sex ChestPainType RestingBP Cholesterol FastingBS RestingECG MaxHR
1  40   M           ATA       140         289         0     Normal   172
2  49   F           NAP       160         180         0     Normal   156
3  37   M           ATA       130         283         0         ST    98
4  48   F           ASY       138         214         0     Normal   108
5  54   M           NAP       150         195         0     Normal   122
6  39   M           NAP       120         339         0     Normal   170
  ExerciseAngina Oldpeak Heart_Disease SexF SexM ExerciseAnginaN
1              N     0.0            NO    0    1               1
2              N     1.0           YES    1    0               1
3              N     0.0            NO    0    1               1
4              Y     1.5           YES    1    0               0
5              N     0.0            NO    0    1               1
6              N     0.0            NO    0    1               1
  ExerciseAnginaY ChestPainTypeASY ChestPainTypeATA ChestPainTypeNAP
1               0                0                1                0
2               0                0                0                1
3               0                0                1                0
4               1                1                0                0
5               0                0                0                1
6               0                0                0                1
  ChestPainTypeTA RestingECGLVH RestingECGNormal RestingECGST
1               0             0                1            0
2               0             0                1            0
3               0             0                0            1
4               0             0                1            0
5               0             0                1            0
6               0             0                1            0</code></pre>
</div>
</div>
</section>
</section>
<section id="split-the-data" class="level3">
<h3 class="anchored" data-anchor-id="split-the-data">Split the Data</h3>
<blockquote class="blockquote">
<p>Prior to fitting a model, we need to split the data into train and test data sets. We can do this with the createDataParticion() function from the caret package. This includes at first setting the seed so that the random number generator used for random number generation/splitting from data sets can be reproducible.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Set the seed so random number generation can be replicated.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">90</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(heart_4<span class="sc">$</span>Heart_Disease, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>heartTrain <span class="ot">&lt;-</span> heart_4[trainIndex, ]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>heartTest <span class="ot">&lt;-</span> heart_4[<span class="sc">-</span>trainIndex, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-using-knn" class="level3">
<h3 class="anchored" data-anchor-id="fitting-using-knn">Fitting using kNN</h3>
<blockquote class="blockquote">
<p>The first model used to fit the data will be the kNN model. Using the caret package, I first set a trainControl method. In this case, it is using repeated cross-validation. This means that a cross-validation step is carried out, in our case with 10 subsets, but the CV is also repeated. In our case, we will repeat 3 times and essentially end with an average of the results of the 3 repetitions.</p>
</blockquote>
<blockquote class="blockquote">
<p>This training control method is set as an object and entered as an argument for the ultimate goal in the train() function. This train() function is from the caret package and will be used to train the data set to determine an optimal k value.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>trctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3333</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>knn_fit <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span>., <span class="at">data =</span> heartTrain, <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a> <span class="at">trControl=</span>trctrl,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a> <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a> <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">k =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">40</span>)),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a> <span class="at">tuneLength =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Given the computational requirements of the above training, I’ll setup a separate code chunk to show the knn_fit result:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>knn_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

523 samples
 21 predictor
  2 classes: 'NO', 'YES' 

Pre-processing: centered (17), scaled (17) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 470, 471, 470, 471, 471, 471, ... 
Resampling results across tuning parameters:

  k   Accuracy   Kappa    
   1  0.7424407  0.4821460
   2  0.7539308  0.5056215
   3  0.7896226  0.5769802
   4  0.7864296  0.5706019
   5  0.7972424  0.5923821
   6  0.7921746  0.5824353
   7  0.7921505  0.5824437
   8  0.7927431  0.5837131
   9  0.7934446  0.5847194
  10  0.8024311  0.6027240
  11  0.8037010  0.6053197
  12  0.8043299  0.6065235
  13  0.8037252  0.6055844
  14  0.8005201  0.5991073
  15  0.8017779  0.6017509
  16  0.7998791  0.5980063
  17  0.8082003  0.6146862
  18  0.7999153  0.5981801
  19  0.8011490  0.6005713
  20  0.8024190  0.6032962
  21  0.7998911  0.5982057
  22  0.7985728  0.5954368
  23  0.8024190  0.6034734
  24  0.7992259  0.5971602
  25  0.8062409  0.6112760
  26  0.8031084  0.6048683
  27  0.8056362  0.6100904
  28  0.8069424  0.6125765
  29  0.8005685  0.6000558
  30  0.8063256  0.6116522
  31  0.8025036  0.6040191
  32  0.7999395  0.5988407
  33  0.8005926  0.6005130
  34  0.8005685  0.6003643
  35  0.8043662  0.6079941
  36  0.8094582  0.6182223
  37  0.8069182  0.6132477
  38  0.8075714  0.6146415
  39  0.8062651  0.6119919
  40  0.8082003  0.6160253

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 36.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The above result can now be tested using prediction and assessed for accuracy using the confusionMatrix() function. The first step is to actually generate a predicted observation dataframe based on our model fit.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_fit, <span class="at">newdata =</span> heartTest)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>test_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] YES NO  NO  NO  NO  NO  NO  NO  YES NO  YES YES YES YES YES NO  NO  YES
 [19] NO  NO  NO  YES YES NO  YES YES NO  NO  NO  YES NO  NO  YES NO  NO  NO 
 [37] NO  NO  YES YES NO  YES YES NO  NO  NO  YES NO  YES NO  YES YES NO  YES
 [55] YES NO  YES NO  NO  NO  NO  NO  YES NO  NO  YES NO  NO  NO  YES NO  NO 
 [73] NO  NO  NO  YES YES YES NO  NO  NO  YES YES NO  NO  YES NO  YES NO  NO 
 [91] NO  YES YES YES NO  NO  YES YES YES YES YES YES NO  YES YES YES YES YES
[109] YES NO  YES YES YES YES YES YES YES YES YES NO  NO  YES NO  YES YES YES
[127] YES YES NO  NO  NO  YES NO  YES NO  YES YES NO  NO  YES YES YES NO  NO 
[145] NO  NO  NO  YES NO  NO  NO  NO  NO  NO  YES NO  YES NO  NO  NO  YES YES
[163] NO  YES NO  YES NO  NO  NO  YES YES YES NO  NO  YES YES YES NO  YES NO 
[181] YES YES YES NO  YES YES NO  YES NO  YES YES YES YES YES NO  YES YES YES
[199] NO  NO  NO  NO  YES NO  YES NO  YES NO  YES NO  NO  NO  NO  YES NO  NO 
[217] YES NO  NO  NO  YES YES NO 
Levels: NO YES</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I’m not able to innately assess accuracy from that output, so here’s the confusionMatrix function to help assess:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(test_pred, heartTest<span class="sc">$</span>Heart_Disease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction NO YES
       NO  95  20
       YES 22  86
                                          
               Accuracy : 0.8117          
                 95% CI : (0.7541, 0.8608)
    No Information Rate : 0.5247          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.6227          
                                          
 Mcnemar's Test P-Value : 0.8774          
                                          
            Sensitivity : 0.8120          
            Specificity : 0.8113          
         Pos Pred Value : 0.8261          
         Neg Pred Value : 0.7963          
             Prevalence : 0.5247          
         Detection Rate : 0.4260          
   Detection Prevalence : 0.5157          
      Balanced Accuracy : 0.8116          
                                          
       'Positive' Class : NO              
                                          </code></pre>
</div>
</div>
</section>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h3>
<blockquote class="blockquote">
<p>Eventually, I would like to be able to compare several different prediction models for supervised learning. Given that the data set in question is attempting to predict a factor outcome of whether an individual has heart disease or not. The next step in this process is to use the previously processed data set and fit several different logistic regression models to it.</p>
</blockquote>
<blockquote class="blockquote">
<p>For this analysis, variables can be characters (i.e.&nbsp;dummy variables are not necessary), so I will start with the “heart_3” data set, as opposed to the “heart_4” set used for the kNN investigation.</p>
</blockquote>
<blockquote class="blockquote">
<p>The three models I will use are: / 1) Age 2) Age and Cholesterol, with interaction effects 3) Age, Cholesterol, and Sex, with interaction effects</p>
</blockquote>
<blockquote class="blockquote">
<p>Before beginning, I’d like to construct a plot with Age vs the proportion of observations having Heart Disease. While Age feels like a reasonable assumption to show a correlation to Heart Disease status, I’d like to visualize it first. This plot requires using ‘heart_2’, which was pre-factorization of Heart Disease variable, because the proportion requires doubles to be calculated.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>distSum <span class="ot">&lt;-</span> heart_2 <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">propDisease =</span> <span class="fu">mean</span>(HeartDisease), <span class="at">n =</span> <span class="fu">n</span>())</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(distSum, <span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">y=</span>propDisease, <span class="at">size =</span> n)) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="fu">aes</span>(<span class="at">size =</span> n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>It does seem like there’s somewhat of a linear relationship, but now I’ll start with the actual model development, starting with simply Disease status based on Age. These models will use the heart_3 data set, constructed with Heart Disease as factor variable.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a train &amp; test data set from the heart_3 set</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Set the seed so random number generation can be replicated.</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">90</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>train2Index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(heart_3<span class="sc">$</span>Heart_Disease, <span class="at">p =</span> <span class="fl">0.7</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>heartTrain2 <span class="ot">&lt;-</span> heart_3[trainIndex, ]</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>heartTest2 <span class="ot">&lt;-</span> heart_3[<span class="sc">-</span>trainIndex, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-1" class="level4">
<h4 class="anchored" data-anchor-id="model-1">Model 1:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glm fit based on Age as the only predictor</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>(glmFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> Age,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heartTrain2,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

523 samples
  1 predictor
  2 classes: 'NO', 'YES' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 471, 470, 470, 471, 471, 471, ... 
Resampling results:

  Accuracy   Kappa    
  0.6329584  0.2630993</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>summary</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glmFit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.44964    0.55684  -6.195 5.83e-10 ***
Age          0.06321    0.01030   6.137 8.41e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 724.02  on 522  degrees of freedom
Residual deviance: 682.25  on 521  degrees of freedom
AIC: 686.25

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="model-2" class="level4">
<h4 class="anchored" data-anchor-id="model-2">Model 2:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glm fit based on Age &amp; Cholesterol as predictors, as well as their</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co">#interaction effects.</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>(glmFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> Age<span class="sc">*</span>Cholesterol,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heartTrain,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

523 samples
  2 predictor
  2 classes: 'NO', 'YES' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 471, 471, 471, 471, 470, 471, ... 
Resampling results:

  Accuracy   Kappa    
  0.6279028  0.2562873</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Summary</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glmFit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -1.255e+01  2.631e+00  -4.769 1.85e-06 ***
Age                2.162e-01  4.811e-02   4.494 7.00e-06 ***
Cholesterol        3.638e-02  1.015e-02   3.584 0.000339 ***
`Age:Cholesterol` -6.102e-04  1.848e-04  -3.302 0.000961 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 724.02  on 522  degrees of freedom
Residual deviance: 663.25  on 519  degrees of freedom
AIC: 671.25

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="model-3" class="level4">
<h4 class="anchored" data-anchor-id="model-3">Model 3:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glm fit based on Age, Cholesterol, and Sex as predictors</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>(glmFit3 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> Age <span class="sc">+</span> Cholesterol <span class="sc">+</span> Sex,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> heartTrain,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"glm"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl=</span>trctrl,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">"binomial"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized Linear Model 

523 samples
  3 predictor
  2 classes: 'NO', 'YES' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 470, 471, 471, 470, 471, 471, ... 
Resampling results:

  Accuracy   Kappa    
  0.6895985  0.3799412</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Summary</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glmFit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
NULL

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -6.709550   0.826786  -8.115 4.85e-16 ***
Age          0.067940   0.011153   6.092 1.12e-09 ***
Cholesterol  0.006039   0.001698   3.557 0.000375 ***
SexM         1.948813   0.264209   7.376 1.63e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 724.02  on 522  degrees of freedom
Residual deviance: 608.53  on 519  degrees of freedom
AIC: 616.53

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The models have AIC values: Model 1 AIC = 686.25 Model 2 AIC = 671.25 Model 3 AIC = 616.53</p>
</blockquote>
<blockquote class="blockquote">
<p>Of the models selected, the 3rd model has the lowest AIC and the best fit</p>
</blockquote>
</section>
<section id="predicting-and-analyzing-model-results" class="level4">
<h4 class="anchored" data-anchor-id="predicting-and-analyzing-model-results">Predicting and Analyzing model results</h4>
<blockquote class="blockquote">
<p>I’ll use the method used in the “Fitting using kNN” section above to predict responses based on the logistic regression models above. I’ll also use the method of cross-validation used to get an “average” response outcome.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">confusionMatrix</span>(glmFit3, <span class="at">newdata =</span> heartTest2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated (10 fold, repeated 3 times) Confusion Matrix 

(entries are percentual average cell counts across resamples)
 
          Reference
Prediction   NO  YES
       NO  34.9 13.7
       YES 17.3 34.1
                            
 Accuracy (average) : 0.6896</code></pre>
</div>
</div>
</section>
</section>
<section id="tree-models" class="level3">
<h3 class="anchored" data-anchor-id="tree-models">Tree Models</h3>
<blockquote class="blockquote">
<p>Similar to the above sequence, I will experiment with various tree models and determine which one of the three is the best model/fit.</p>
</blockquote>
<blockquote class="blockquote">
<p>Model 1: Sex &amp; Chest Pain Type Model 2: Resting BP &amp; Resting ECG Model 3: Age, Sex, Resting BP, and interaction effects</p>
</blockquote>
<section id="tree-model-1" class="level4">
<h4 class="anchored" data-anchor-id="tree-model-1">Tree Model 1:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>(treeFit1 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> Sex<span class="sc">*</span>ChestPainType,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> heartTrain2,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rpart"</span>,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl=</span>trctrl,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.1</span>, <span class="at">by =</span> <span class="fl">0.001</span>)),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

523 samples
  2 predictor
  2 classes: 'NO', 'YES' 

Pre-processing: centered (7), scaled (7) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 471, 471, 471, 471, 470, 470, ... 
Resampling results across tuning parameters:

  cp     Accuracy   Kappa    
  0.000  0.7484519  0.4944257
  0.001  0.7484519  0.4944257
  0.002  0.7484519  0.4944257
  0.003  0.7484519  0.4944257
  0.004  0.7484519  0.4944257
  0.005  0.7516449  0.5010932
  0.006  0.7516449  0.5010932
  0.007  0.7516449  0.5010932
  0.008  0.7516449  0.5010932
  0.009  0.7554669  0.5089632
  0.010  0.7554669  0.5089632
  0.011  0.7554669  0.5089632
  0.012  0.7554669  0.5089632
  0.013  0.7554669  0.5089632
  0.014  0.7611998  0.5208814
  0.015  0.7611998  0.5208814
  0.016  0.7611998  0.5208814
  0.017  0.7611998  0.5208814
  0.018  0.7611998  0.5208814
  0.019  0.7611998  0.5208814
  0.020  0.7611998  0.5208814
  0.021  0.7611998  0.5208814
  0.022  0.7611998  0.5208814
  0.023  0.7611998  0.5208814
  0.024  0.7611998  0.5208814
  0.025  0.7611998  0.5208814
  0.026  0.7611998  0.5208814
  0.027  0.7611998  0.5208814
  0.028  0.7611998  0.5208814
  0.029  0.7611998  0.5208814
  0.030  0.7611998  0.5208814
  0.031  0.7611998  0.5208814
  0.032  0.7611998  0.5208814
  0.033  0.7611998  0.5208814
  0.034  0.7611998  0.5208814
  0.035  0.7611998  0.5208814
  0.036  0.7573537  0.5134024
  0.037  0.7573537  0.5134024
  0.038  0.7573537  0.5134024
  0.039  0.7573537  0.5134024
  0.040  0.7573537  0.5134024
  0.041  0.7573537  0.5134024
  0.042  0.7573537  0.5134024
  0.043  0.7573537  0.5134024
  0.044  0.7573537  0.5134024
  0.045  0.7446299  0.4889228
  0.046  0.7446299  0.4889228
  0.047  0.7446299  0.4889228
  0.048  0.7446299  0.4889228
  0.049  0.7267537  0.4543038
  0.050  0.7267537  0.4543038
  0.051  0.7267537  0.4543038
  0.052  0.7267537  0.4543038
  0.053  0.7267537  0.4543038
  0.054  0.7229076  0.4469751
  0.055  0.7229076  0.4469751
  0.056  0.7229076  0.4469751
  0.057  0.7229076  0.4469751
  0.058  0.7197388  0.4414069
  0.059  0.7197388  0.4414069
  0.060  0.7197388  0.4414069
  0.061  0.7197388  0.4414069
  0.062  0.7197388  0.4414069
  0.063  0.7197388  0.4422349
  0.064  0.7197388  0.4422349
  0.065  0.7197388  0.4422349
  0.066  0.7197388  0.4422349
  0.067  0.7210208  0.4450080
  0.068  0.7210208  0.4450080
  0.069  0.7210208  0.4450080
  0.070  0.7210208  0.4450080
  0.071  0.7210208  0.4450080
  0.072  0.7210208  0.4450080
  0.073  0.7210208  0.4450080
  0.074  0.7210208  0.4450080
  0.075  0.7210208  0.4450080
  0.076  0.7229439  0.4490507
  0.077  0.7229439  0.4490507
  0.078  0.7229439  0.4490507
  0.079  0.7229439  0.4490507
  0.080  0.7229439  0.4490507
  0.081  0.7229439  0.4490507
  0.082  0.7229439  0.4490507
  0.083  0.7229439  0.4490507
  0.084  0.7229439  0.4490507
  0.085  0.7229439  0.4490507
  0.086  0.7229439  0.4490507
  0.087  0.7229439  0.4490507
  0.088  0.7229439  0.4490507
  0.089  0.7229439  0.4490507
  0.090  0.7229439  0.4490507
  0.091  0.7229439  0.4490507
  0.092  0.7229439  0.4490507
  0.093  0.7229439  0.4490507
  0.094  0.7210208  0.4453363
  0.095  0.7210208  0.4453363
  0.096  0.7210208  0.4453363
  0.097  0.7210208  0.4453363
  0.098  0.7210208  0.4453363
  0.099  0.7210208  0.4453363
  0.100  0.7210208  0.4453363

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was cp = 0.035.</code></pre>
</div>
</div>
</section>
<section id="tree-model-2" class="level4">
<h4 class="anchored" data-anchor-id="tree-model-2">Tree Model 2:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>(treeFit2 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> RestingBP <span class="sc">+</span> RestingECG,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> heartTrain2,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rf"</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl=</span>trctrl,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">mtry =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest 

523 samples
  2 predictor
  2 classes: 'NO', 'YES' 

Pre-processing: centered (3), scaled (3) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 471, 471, 470, 470, 471, 471, ... 
Resampling results across tuning parameters:

  mtry  Accuracy   Kappa     
   1    0.5551040  0.09562277
   2    0.5506410  0.08710945
   3    0.5468795  0.08058912
   4    0.5449927  0.07684816
   5    0.5417755  0.07027804
   6    0.5443517  0.07532134
   7    0.5373125  0.06145278
   8    0.5424165  0.07137642
   9    0.5392235  0.06542680
  10    0.5360305  0.05902229

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was mtry = 1.</code></pre>
</div>
</div>
</section>
<section id="tree-model-3" class="level4">
<h4 class="anchored" data-anchor-id="tree-model-3">Tree Model 3:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(treeFit3 <span class="ot">&lt;-</span> <span class="fu">train</span>(Heart_Disease <span class="sc">~</span> Age<span class="sc">*</span>Sex<span class="sc">*</span>RestingBP,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> heartTrain2,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"gbm"</span>,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">trControl=</span>trctrl,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">n.trees =</span> <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>),</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">interaction.depth =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">shrinkage =</span> <span class="fu">c</span>(<span class="fl">0.1</span>),</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">n.minobsinnode =</span> <span class="fu">c</span>(<span class="dv">10</span>)),</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">10</span>,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic Gradient Boosting 

523 samples
  3 predictor
  2 classes: 'NO', 'YES' 

Pre-processing: centered (7), scaled (7) 
Resampling: Cross-Validated (10 fold, repeated 3 times) 
Summary of sample sizes: 470, 471, 471, 470, 471, 471, ... 
Resampling results across tuning parameters:

  interaction.depth  n.trees  Accuracy   Kappa    
  1                   25      0.6710450  0.3408158
  1                   50      0.6710329  0.3414519
  1                  100      0.6684930  0.3368812
  1                  200      0.6799952  0.3591444
  2                   25      0.6729560  0.3460858
  2                   50      0.6677673  0.3352570
  2                  100      0.6799347  0.3596900
  2                  200      0.6709845  0.3411997
  3                   25      0.6710692  0.3412681
  3                   50      0.6705128  0.3396435
  3                  100      0.6671626  0.3334723
  3                  200      0.6595549  0.3181688

Tuning parameter 'shrinkage' was held constant at a value of 0.1

Tuning parameter 'n.minobsinnode' was held constant at a value of 10
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were n.trees = 200, interaction.depth =
 1, shrinkage = 0.1 and n.minobsinnode = 10.</code></pre>
</div>
</div>
</section>
<section id="predicting-and-analyzing-model-results-1" class="level4">
<h4 class="anchored" data-anchor-id="predicting-and-analyzing-model-results-1">Predicting and Analyzing Model Results</h4>
<blockquote class="blockquote">
<p>We will use the confusionMatrix() function to asess accuray for each of the 3 Tree Models fitted above.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For Tree Model 1: Classification Tree Model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">confusionMatrix</span>(treeFit1, <span class="at">newdata =</span> heartTest2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated (10 fold, repeated 3 times) Confusion Matrix 

(entries are percentual average cell counts across resamples)
 
          Reference
Prediction   NO  YES
       NO  41.1 12.8
       YES 11.1 35.0
                           
 Accuracy (average) : 0.761</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For Tree Model 2: Random Forest</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">confusionMatrix</span>(treeFit2, <span class="at">newdata =</span> heartTest2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated (10 fold, repeated 3 times) Confusion Matrix 

(entries are percentual average cell counts across resamples)
 
          Reference
Prediction   NO  YES
       NO  38.2 30.5
       YES 14.0 17.3
                            
 Accuracy (average) : 0.5551</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For Tree Model 3: Boosted Tree</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">confusionMatrix</span>(treeFit3, <span class="at">newdata=</span>heartTest2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cross-Validated (10 fold, repeated 3 times) Confusion Matrix 

(entries are percentual average cell counts across resamples)
 
          Reference
Prediction   NO  YES
       NO  35.7 15.5
       YES 16.5 32.3
                            
 Accuracy (average) : 0.6801</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The results from the above assessments give the following:</p>
</blockquote>
<blockquote class="blockquote">
<p>Classification Tree (Sex, ChestPainType, and interaction effects) Accuracy: 0.761</p>
</blockquote>
<blockquote class="blockquote">
<p>Random Forest (Resting BP &amp; Resting ECG) Accuracy: 0.5551</p>
</blockquote>
<blockquote class="blockquote">
<p>Boosted Tree (Age, Sex, Resting BP, and interaction effects) Accuracy: 0.6801</p>
</blockquote>
</section>
</section>
<section id="wrap-up" class="level3">
<h3 class="anchored" data-anchor-id="wrap-up">Wrap Up</h3>
<blockquote class="blockquote">
<p>Given the accuracy measurements of all preceding models, the model with the highest accuracy when acting on the test set is the Classification Tree model with Sex, ChestPainType, and their interaction effects. With a model accuracy of 0.761.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>